import Head from 'next/head'
import ButtonConnect from './components/ButtonConnect'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="header">
          <img src="logo.svg"></img>
          <div className="header-control">
            <div className="header-phone">
              <h2>+7 (911) 99-91-707</h2>
              <p>Ежедневно с 9:00 до 23:00</p>
            </div>
            <ButtonConnect/>
          </div>
        </div>
      </div>
    </>
  )
}
